# alpine-r36s (RK3326, aarch64/musl) — derived from upstream r36s (armhf/glibc)
ARCH = $(MYARCH)
LIBS =
SDL = SDL2
MY_CFLAGS = -DDRM_MODE_PROP_EXTENDED_TYPE=0x0000ffc0 -D_FILE_OFFSET_BITS=64
MY_LDFLAGS = -ldrm -lsamplerate
MY_INCDIR = -I$(PREFIX)/include/libdrm
